In [1]:
import pandas as pd
from pathlib import Path
from IPython.display import display

data_dir = Path('data')
long_table1 = pd.read_pickle(data_dir /'long_table.pkz')
long_table2 = pd.read_pickle(data_dir /'long_table_2.0.pkz')

In [54]:
gender_F = long_table2[long_table2['gender'] == 'F'].groupby('site_id_l').nunique()
female = gender_F.subjectkey
gender_F

,collection_id,tbl_id,dataset_id,subjectkey,src_subject_id,interview_date,interview_age,gender,eventname,tbl_visitid,...,tfmri_mid_all_sem_dof,tfmri_sst_all_beta_dof,tfmri_sst_all_sem_dof,tfmri_nback_all_beta_dof,tfmri_nback_all_sem_dof,mrif_score,mrif_hydrocephalus,mrif_herniation,mr_findings_ok,qc_ok
site_id_l,,,,,,,,,,,,,,,,,,,,,
site01,1,3284,22,148,148,131,26,1,1,148,...,61,86,86,74,74,4,1,1,2,2
site02,1,4681,22,214,214,134,25,1,1,214,...,62,75,75,80,80,4,1,1,2,2
site03,1,5205,22,239,239,200,26,1,1,239,...,74,96,96,87,87,4,1,1,2,2
site04,1,3838,22,174,174,124,25,1,1,174,...,66,68,68,70,70,4,1,1,2,2
site05,1,2842,22,127,127,110,25,1,1,127,...,66,68,68,69,69,3,1,1,2,2
site06,1,4739,22,217,217,194,26,1,1,217,...,82,91,91,97,97,3,1,1,2,2
site07,1,2557,22,114,114,93,26,1,1,114,...,55,65,65,63,63,4,1,1,2,2
site08,1,1648,22,73,73,67,22,1,1,73,...,38,47,47,43,43,3,1,1,2,2
site09,1,3516,22,159,159,129,25,1,1,159,...,77,98,98,98,98,3,1,1,2,2
site10,1,4090,22,185,185,161,26,1,1,185,...,91,100,100,95,95,4,2,1,2,2
site11,1,3142,22,141,141,123,26,1,1,141,...,75,87,87,74,74,3,1,1,2,2
site12,1,4726,22,217,217,175,25,1,1,217,...,89,112,112,105,105,5,1,1,2,2
site13,1,4367,22,200,200,175,26,1,1,200,...,89,100,100,99,99,3,1,1,2,2
site14,1,4824,22,222,222,147,25,1,1,222,...,78,105,105,101,101,3,1,1,2,2
site15,1,2784,22,124,124,122,25,1,1,124,...,86,92,92,91,91,4,1,1,2,2
site16,1,8353,22,398,398,290,26,1,1,398,...,98,117,117,101,101,4,1,1,2,2
site17,1,4402,22,200,200,163,25,1,1,200,...,86,100,100,101,101,4,1,1,2,2
site18,1,2065,22,91,91,86,24,1,1,91,...,49,50,50,51,51,4,1,1,2,2
site19,1,3614,22,163,163,124,26,1,1,163,...,89,93,93,82,82,4,1,1,2,2
site20,1,5186,22,238,238,171,24,1,1,238,...,109,127,127,120,120,3,1,1,2,2
site21,1,4157,22,189,189,158,25,1,1,189,...,92,104,104,100,100,5,1,1,2,2
site22,1,275,22,12,12,11,9,1,1,12,...,8,10,10,12,12,3,1,1,2,2

In [63]:
gender_M = long_table2[long_table2['gender'] == 'M'].groupby('site_id_l').nunique()
display(gender_M.subjectkey)

site_id_l
site01    144
site02    236
site03    224
site04    167
site05    123
site06    209
site07    125
site08     67
site09    140
site10    181
site11    140
site12    221
site13    197
site14    229
site15    126
site16    467
site17    224
site18    118
site19    153
site20    243
site21    191
site22      7
Name: subjectkey, dtype: int64

In [3]:
Months = long_table2.groupby('interview_age').nunique()
# display(Months)
Month_107 = long_table2[long_table2['interview_age'] == 107].groupby('site_id_l').nunique()
display(Month_107.subjectkey)
Month_108 = long_table2[long_table2['interview_age'] == 108].groupby('site_id_l').nunique()
Month_109 = long_table2[long_table2['interview_age'] == 109].groupby('site_id_l').nunique()
Month_110 = long_table2[long_table2['interview_age'] == 110].groupby('site_id_l').nunique()
Month_111 = long_table2[long_table2['interview_age'] == 111].groupby('site_id_l').nunique()
Month_112 = long_table2[long_table2['interview_age'] == 112].groupby('site_id_l').nunique()
Month_113 = long_table2[long_table2['interview_age'] == 113].groupby('site_id_l').nunique()
Month_114 = long_table2[long_table2['interview_age'] == 114].groupby('site_id_l').nunique()
Month_115 = long_table2[long_table2['interview_age'] == 115].groupby('site_id_l').nunique()
Month_116 = long_table2[long_table2['interview_age'] == 116].groupby('site_id_l').nunique()
Month_117 = long_table2[long_table2['interview_age'] == 117].groupby('site_id_l').nunique()
Month_118 = long_table2[long_table2['interview_age'] == 118].groupby('site_id_l').nunique()
Month_119 = long_table2[long_table2['interview_age'] == 119].groupby('site_id_l').nunique()
Month_120 = long_table2[long_table2['interview_age'] == 120].groupby('site_id_l').nunique()
Month_121 = long_table2[long_table2['interview_age'] == 121].groupby('site_id_l').nunique()
Month_122 = long_table2[long_table2['interview_age'] == 122].groupby('site_id_l').nunique()
Month_123 = long_table2[long_table2['interview_age'] == 123].groupby('site_id_l').nunique()
Month_124 = long_table2[long_table2['interview_age'] == 124].groupby('site_id_l').nunique()
Month_125 = long_table2[long_table2['interview_age'] == 125].groupby('site_id_l').nunique()
Month_126 = long_table2[long_table2['interview_age'] == 126].groupby('site_id_l').nunique()
Month_127 = long_table2[long_table2['interview_age'] == 127].groupby('site_id_l').nunique()
Month_128 = long_table2[long_table2['interview_age'] == 128].groupby('site_id_l').nunique()
Month_129 = long_table2[long_table2['interview_age'] == 129].groupby('site_id_l').nunique()
Month_130 = long_table2[long_table2['interview_age'] == 130].groupby('site_id_l').nunique()
Month_131 = long_table2[long_table2['interview_age'] == 131].groupby('site_id_l').nunique()
Month_132 = long_table2[long_table2['interview_age'] == 132].groupby('site_id_l').nunique()

site_id_l
site01    26
site02    26
site03    26
site04    26
site05    26
site06    26
site07    26
site08    26
site09    25
site10    26
site11    26
site12    26
site13    26
site14    25
site15    25
site16    26
site17    26
site18    26
site19    26
site20    25
site21    25
site22    12
Name: interview_age, dtype: int64

site_id_l
site01     6
site02     3
site03     9
site04     5
site05     1
site06     5
site07     5
site08     1
site09     3
site10     5
site11     5
site12    10
site13     6
site15     4
site16    16
site17     9
site18     1
site19     1
site21     2
Name: subjectkey, dtype: int64

In [76]:
table['Site'] = long_table2['site_id_l'].unique()
table['Female'] = gender_F['subjectkey']
table['Male'] = gender_M['subjectkey']
table['Month 107'] = Month_107['subjectkey']
table['Month 108'] = Month_108['subjectkey']
table['Month 109'] = Month_109['subjectkey']
table['Month 110'] = Month_110['subjectkey']
table['Month 111'] = Month_111['subjectkey']
table['Month 112'] = Month_112['subjectkey']
table['Month 113'] = Month_113['subjectkey']
table['Month 114'] = Month_114['subjectkey']
table['Month 115'] = Month_115['subjectkey']
table['Month 116'] = Month_116['subjectkey']
table['Month 117'] = Month_117['subjectkey']
table['Month 118'] = Month_118['subjectkey']
table['Month 119'] = Month_119['subjectkey']
table['Month 120'] = Month_120['subjectkey']
table['Month 121'] = Month_121['subjectkey']
table['Month 122'] = Month_122['subjectkey']
table['Month 123'] = Month_123['subjectkey']
table['Month 124'] = Month_124['subjectkey']
table['Month 125'] = Month_125['subjectkey']
table['Month 126'] = Month_126['subjectkey']
table['Month 127'] = Month_127['subjectkey']
table['Month 128'] = Month_128['subjectkey']
table['Month 129'] = Month_129['subjectkey']
table['Month 130'] = Month_130['subjectkey']
table['Month 131'] = Month_131['subjectkey']
table['Month 132'] = Month_132['subjectkey']
table_df = pd.DataFrame(data = table)
table_df

,Site,Female,Male,Month 107,Month 108,Month 109,Month 110,Month 111,Month 112,Month 113,...,Month 123,Month 124,Month 125,Month 126,Month 127,Month 128,Month 129,Month 130,Month 131,Month 132
site01,site06,148,144,6.0,31.0,19,8.0,11.0,10.0,5,...,11.0,14.0,17,11,13.0,8,11.0,8,12,5.0
site02,site12,214,236,3.0,17.0,11,22.0,9.0,13.0,18,...,11.0,13.0,14,17,7.0,20,19.0,38,53,8.0
site03,site04,239,224,9.0,40.0,29,27.0,14.0,19.0,9,...,19.0,17.0,17,17,17.0,14,22.0,17,21,2.0
site04,site16,174,167,5.0,44.0,29,11.0,16.0,14.0,5,...,10.0,7.0,14,14,15.0,9,15.0,12,16,6.0
site05,site01,127,123,1.0,24.0,14,17.0,10.0,11.0,5,...,8.0,11.0,9,11,5.0,13,5.0,9,10,3.0
site06,site10,217,209,5.0,24.0,23,23.0,18.0,13.0,15,...,24.0,19.0,21,12,22.0,10,19.0,13,15,5.0
site07,site20,114,125,5.0,19.0,15,12.0,14.0,11.0,4,...,9.0,8.0,10,5,9.0,10,6.0,15,10,2.0
site08,site19,73,67,1.0,10.0,7,4.0,6.0,5.0,1,...,4.0,7.0,2,5,4.0,6,5.0,6,9,2.0
site09,site13,159,140,3.0,16.0,12,15.0,14.0,9.0,10,...,6.0,13.0,17,10,11.0,13,16.0,9,22,NaN
site10,site07,185,181,5.0,37.0,26,13.0,16.0,9.0,14,...,11.0,21.0,12,21,10.0,12,21.0,18,11,7.0
site11,site02,141,140,5.0,35.0,24,16.0,12.0,9.0,4,...,13.0,13.0,12,9,8.0,8,8.0,9,15,2.0
site12,site11,217,221,10.0,42.0,23,13.0,17.0,19.0,12,...,18.0,16.0,17,15,14.0,13,19.0,18,22,2.0
site13,site21,200,197,6.0,28.0,27,18.0,24.0,15.0,17,...,16.0,11.0,13,15,10.0,12,7.0,10,21,3.0
site14,site14,222,229,NaN,10.0,8,6.0,5.0,6.0,6,...,15.0,16.0,13,22,22.0,24,28.0,38,51,6.0
site15,site09,124,126,4.0,19.0,7,5.0,12.0,9.0,14,...,5.0,10.0,10,5,7.0,11,12.0,9,17,NaN
site16,site17,398,467,16.0,82.0,67,60.0,36.0,20.0,23,...,24.0,36.0,29,23,43.0,22,38.0,30,54,16.0
site17,site03,200,224,9.0,56.0,24,26.0,12.0,12.0,14,...,13.0,18.0,14,18,16.0,11,16.0,6,22,1.0
site18,site18,91,118,1.0,6.0,15,14.0,10.0,6.0,11,...,7.0,9.0,6,5,14.0,12,5.0,13,11,2.0
site19,site15,163,153,1.0,6.0,3,11.0,5.0,9.0,13,...,18.0,18.0,13,9,8.0,13,11.0,18,24,2.0
site20,site08,238,243,NaN,4.0,4,8.0,11.0,6.0,23,...,34.0,17.0,26,22,31.0,24,22.0,15,17,1.0
site21,site05,189,191,2.0,25.0,17,17.0,15.0,17.0,16,...,14.0,10.0,18,16,25.0,20,16.0,17,15,NaN
site22,site22,12,7,NaN,NaN,1,NaN,NaN,NaN,1,...,NaN,NaN,2,2,NaN,2,NaN,1,2,1.0